### ISSUE TITLE
Different shapes of track.stems depending in DB(is_wav)

### ISSUE THREAD

**Issue by carlthome** [sigsep/sigsep-mus-db#4]
After [decoding](https://github.com/sigsep/sigsep-mus-io#decode-sigsep-mus-to-wav-format), I ran into what feels like a bug (if not, sorry!):

```
mus = musdb.DB()
tracks = mus.load_mus_tracks()
print(tracks[0].stems.shape)
```
>(5, 7552000, 2)

```
mus = musdb.DB(is_wav=True)
tracks = mus.load_mus_tracks('train')
print(tracks[0].stems.shape)
```
>(7552000, 2)

Also, when `is_wav=True`, `load_mus_tracks` returns an empty list if `subsets=''`.

**Comment by faroit** [comment]
oops, indeed... thanks for finding this. 
In the end, I did not use the `.stems` property in this tool, so I haven't done proper unit tests for it. 
I will fix it today and make a new release.

**Comment by faroit** [comment]
Reproduced in d0b06b

**Comment by faroit** [comment]
should be fixed in  2405d18 

@carlthome can you please check if this works as expected?

**Comment by carlthome** [comment]
Shapes look right now. Thanks!

```python
mus = musdb.DB(is_wav=True)
tracks = mus.load_mus_tracks()
```
still fails though (while it works if `is_wav=False`)

**Comment by faroit** [comment]
uh, can you have a look if the sample set produces the same problems? You can create this by running [fetch.sh](https://github.com/sigsep/sigsep-mus-db/blob/master/data/fetch.sh) and [decode.sh](https://github.com/sigsep/sigsep-mus-db/blob/master/data/decode.sh). 

Also do the py.tests run?

**Comment by faroit** [comment]
just double check... your decoded musdb file structure looks like this, right?

<img width="559" alt="screen shot 2018-01-14 at 23 28 23" src="https://user-images.githubusercontent.com/72940/34921458-b63d9bba-f982-11e7-942b-79ec8e5a48ec.png">

**Comment by carlthome** [comment]
Yeah, that's the folder structure after using the Docker scripts for decoding.

I'll go over to using the mp4:s though as they're nicer. I personally would be fine with the `is_wav` option being removed (to make the codebase simpler). Feel free to close this issue!

**Comment by faroit** [comment]
we some other participants using the docker decoded version because they either don't use python or cannot easily install ffmpeg (hello windows users without anaconda)...

Therefore it would still be great to know if there is a bug.

**Comment by faroit** [comment]
probably fixed in v.0.2.1
